[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devUrl = "http://localhost:1420"
frontendDist = "../dist"

[app]
windows = [
  { label = "main", title = "", decorations = false, transparent = true, fullscreen = true, resizable = false, visible = true }
]
withGlobalTauri = true
