[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devUrl = "http://localhost:1420"
frontendDist = "../dist"

[app]
productName = "Tauri Transparent Text Widget"
version = "0.1.0"
identifier = "com.fuuji9.textwidget"
